    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.io.IOException;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import static project.CreateTree.InfixToPostFit;
import static project.CreateTree.expressionTree;

import project.Project;


/**
 *
 * @author s-sys
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public Gui() {//הביטוי
         String infix33="((((((2*3)+(5*5))*((5+2)/(2-1)))+(((2*3)+(5*5))*((5-2)/(2-1))))-((((2*3)+(5*5))*((5+2)*(2-1)))+(((2*3)+(5*5))*((5-2)/(2-1)))))+(((((2*3)-(5*5))*((5-2)/(2-1)))+(((8*3)-(5*5))*((5-2)/(2-1))))-((((2*3)-(5*5))*((6-2)/(2-1)))+(((2*3)+(5*5))*((5-2)/(9-1))))))-((((((2*3)-(5*5))*((5-2)/(2+1)))+(((2*3)+(5*5))*((5+2)/(2-1))))-((((2*3)-(5*5))*((5+2)/(2-1)))+(((2*3)+(5*5))*((5-2)/(2-1)))))+(((((2*3)-(5*5))*((5-2)/(2-1)))+(((2*3)-(5*5))*((5-2)/(2-1))))-((((2*3)-(5*5))*((5-2)/(2-1)))+(((2*3)-(5*5))*((5-2)/(2-1))))))";
        String postfix= InfixToPostFit(infix33);//הפיכת הביטוי תוכי לביטוי סופי
         r = expressionTree(postfix);//בניית עץ לסידרתי
         r2= expressionTree(postfix);//בניית עץ למקבילי
        System.out.println("created tree");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2_s1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelm1 = new javax.swing.JLabel();
        jLabels2 = new javax.swing.JLabel();
        jLabelm2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("חישוב עץ אריתמטי");

        jLabel2_s1.setText("???????");

        jButton2.setText("סידרתי");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("מקבילי");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelm1.setText("???????");

        jLabels2.setText("???????");

        jLabelm2.setText("???????");

        jLabel6.setText("פתרון התרגיל");

        jLabel7.setText("משך זמן הריצה");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelm1)
                            .addComponent(jLabelm2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_s1)
                            .addComponent(jLabels2))
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_s1)
                    .addComponent(jLabelm1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabels2)
                    .addComponent(jLabelm2)
                    .addComponent(jLabel7))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("חישוב עץ אריטמתי");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Node r=null;
    Node r2=null;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      //סידרתי-------------------------------------
       long startTime = System.currentTimeMillis();//שמירת זמן התחלה
       System.out.println("Serial sorting start at " + startTime);
       double x = 0;
        try {
            x =SequentialCalculation.CalculateS(r);//הפעלת הפונקציה הסידרתית
        } catch (InterruptedException | IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        long endTime = System.currentTimeMillis();//שמירת זמן הסיום
        System.out.println("  Serial sorting end at " + endTime);
        System.out.println("--------------סידרתי-------------- serial diff: " + (endTime - startTime));
        long diffTimesequential=endTime-startTime;//שמירת ההפרש של הסידרתי
        String diff=String.valueOf(diffTimesequential);
        jLabels2.setText(diff);//הצגה למסך של זמן הריצה
        String s=String.valueOf(x);
        jLabel2_s1.setText(s);//הצגה במסך
        jButton2.setEnabled(false);
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // מקבילי---------------------------
        ParallelCalculation c=new ParallelCalculation();//בנית עצם מסוג המחלקה של המקבילי
        double x;
         long startTime = System.currentTimeMillis();//זמן התחלה
        System.out.println("Serial sorting start at " + startTime);
        x = c.CalculateMM(r2);//מקבילי
        long endTime = System.currentTimeMillis();//זמן סיום
        System.out.println("  Serial sorting end at " + endTime);
        System.out.println("--------------מקבילי-------------- serial diff: " + (endTime - startTime));//חישוב מס המילי שניות שרצה הפונקציה
        long diffTCalculate=endTime-startTime;//שמירת ההפרש של המקבילי
        String diff=String.valueOf(diffTCalculate);
        jLabelm2.setText(diff);//הצגה למסך של זמן הריצה
        String s=String.valueOf(x);
        jLabelm1.setText(s);//הדפסה למסך
        jButton3.setEnabled(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2_s1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelm1;
    private javax.swing.JLabel jLabelm2;
    private javax.swing.JLabel jLabels2;
    // End of variables declaration//GEN-END:variables

    
}
